### PR TITLE
Add FZF layer

### PR DESCRIPTION
**Pull request by ytang**
I wrote a `+nav/fzf` layer as an alternative to the existing `+nav/fuzzy` layer. Please feel free to merge, discard, or edit anything to your liking. :smile:

### CODE REVIEW

**Comment by Tehnix** [comment]
Awesome! Having people contribute layers is one of the benefits of a "distribution" like this! 

Just one thing, could you also add the layer to the list in the main README? Else it looks ready to merge 🙂

**Comment by ytang** [comment]
Sure, updated README.

One thing I'm not so sure about is where to bind the keys. Right now I'm putting everything under `SPC f`, which makes sense if `SPC f` means not only `+files` but also `+find`. (Consider that `Spacemacs` also has multiple keybinding categories under the same mnemonic, such as `SPC c` for `+compile/comments` and `SPC s` for `+search/symbol`.)

Alternatively, we could distribute them under different categories. For example, `find-file` goes to `SPC f`, `find-buffer` goes to `SPC b`, and the grep-related functions go to something like `SPC s`.

**Comment by Tehnix** [comment]
I think it's very fitting under `+files`, while Spacemacs does name it the same it does also contain the find functionality which this layer brings in. As a default I usually aim to place things somewhat the same places as Spacemacs would, mostly to ease switching back and forth between the two.

W.r.t. `find-buffer`, it finds the file for the buffer, right? I think it's fine in `+files`. For comparison, Spacemacs keeps `show-and-copy-buffer-filename` under there as well. That said, the case could easily be made for buffer also, but I'm fine with the current 👍

**Comment by ytang** [comment]
Thanks for merging! I agree with your judgment, but I'm open to other opinions as well.

BTW, my `find-buffer` in `+nav/fzf` is pretty much the same as your `find-buffer` in `+nav/fuzzy`, i.e., `CtrlPBuffer`.

**Pull request merged**
