### PR TITLE
Add fuzzy search layer

### PR DESCRIPTION
**Pull request by lowski**
Layers dedicated to fuzzy searching.

@Tehnix please check when you have a moment.

### CODE REVIEW

**Comment by Tehnix** [comment]
Perfect! Would it be possible to add it to the main README under current layers?
I would do it myself to help, but unfortunately I’m limited to a phone and an iPad while I’m traveling around Vietnam atm.

Let me know, else I’ll do an update to the README with all the new layers in one fell swoop after these PRa are merged :)

**Comment by lowski** [comment]
@Tehnix thanks for checking PRs. I've updated README.

Btw. I've never been to Vietnam but I highly recommend Thailand and Bali! Enjoy your trip :)

**Comment by Tehnix** [comment]
Perfect :)

Haha thanks! ^_^ Yeah, I’ve heard good about those too :)

**Comment by Tehnix** [comment]
Ah, I should have known that updating the README in multiple PRs would risk merge conflicts - would you have a change to rebase it on current HEAD?

**Comment by lowski** [comment]
@Tehnix PR has been rebased. I will merge it since you already reviewed it.

**Pull request merged**
